config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :listings do
    resources :bookings, except: [:destroy]
  end
  resources :bookings, only: [:destroy]
  get '/my_bookings', to: 'bookings#my_bookings'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  validates :startdate, :finishdate, presence: true
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  validates :title, :description, :price, presence: true
  has_one_attached :photo

  include PgSearch::Model
    pg_search_scope :search_by,
      against: [ [:title, 'A'], [:description, 'C']],
      associated_against: {
        user: [[:first_name, 'B'], [:last_name, 'B']]
      },
      using: {
        tsearch: { prefix: true }
      }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
  has_one_attached :avatar
  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name avatar])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  before_action :set_booking, only: [:show, :edit, :update, :destroy ]
  before_action :set_listing, only: [:new, :create, :edit, :index ]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.listing = @listing
    @booking.user = current_user
    if @booking.save
      redirect_to my_bookings_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @booking.update(booking_params)
    redirect_to my_bookings_path
  end

  def destroy
    @booking.destroy
    redirect_to my_bookings_path
  end

  def my_bookings
    @bookings = Booking.where(user: current_user)
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_listing
    @listing = Listing.find(params[:listing_id])
  end

  def booking_params
    params.require(:booking).permit(:startdate, :finishdate)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query].present?
      @listings = Listing.search_by(params[:query])
    else
      @listings = Listing.all
    end
  end

  def show
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    if @listing.save
      redirect_to listing_path(@listing)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @listing.update(listing_params)
    redirect_to listing_path(@listing)
  end

  def destroy
    @listing.destroy
    redirect_to listings_path
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def listing_params
    params.require(:listing).permit(:title, :description, :price, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
    <h1>Update Booking</h1>
<%= simple_form_for [ @listing,@booking ] do |f| %>
    <%= f.input :startdate, as: :datetime, html5: true, label: 'Start' %>
  <%= f.input :finishdate, as: :datetime, html5: true, label: 'Finish'  %>
  <%= f.submit 'Update Booking', class: 'btn-gradient'%>
<% end %>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<h2>My bookings</h2>
<h2><% @bookings.each do |booking| %></h2>
  <%= booking.listing.title %>
  <p><%= booking.startdate %></p>
  <%= link_to "Edit", edit_listing_booking_path(booking.listing.id, booking)%>
  <%= link_to "Delete", booking_path(booking), method: :delete, data: {confirm: "Are you sure?"}%>
<% end  %>

app/views/bookings/my_bookings.html.erb
<div class="container">
    <h1 class="row justify-content-center">Bookings</h1>
<div class="flex ">
  <div >
    <div class="booking-cards">
      <h2><% @bookings.each do |booking| %></h2>
          <div class="booking-card">
            <img src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="listing-tutor">
            <div class="booking-card-content">
            <p> Tutor: <%= "#{booking.listing.user.first_name} #{booking.listing.user.last_name}" %> </p>
            <p><%= booking.startdate.strftime("#{booking.startdate.day.ordinalize} %B %Y") %></p>
            <p>Subject: <%= booking.listing.title %> </p>
            <p>Time: <%= "#{booking.startdate.strftime("%I:%M%P")} - #{booking.finishdate.strftime("%I:%M%P")}"%></p>

            <div class="booking-card-buttons">
              <%= link_to "Edit", edit_listing_booking_path(booking.listing.id, booking), class: "card-book-button " %>
              <%= link_to "Delete", booking_path(booking), method: :delete, data: {confirm: "Are you sure?"}, class: "card-book-button "%>
            </div>
            </div>
          </div>
      <% end  %>
    </div>
  </div>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
    <h1>New Booking</h1>
<%= simple_form_for [ @listing,@booking ] do |f| %>
  <%= f.input :startdate, as: :datetime, html5: true, label: 'Start' %>
  <%= f.input :finishdate, as: :datetime, html5: true, label: 'Finish'  %>
  <p>Price:<%=  %> </p>
  <%= f.submit 'Create Booking', class: 'btn-gradient'%>
<% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentadev</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/listings/edit.html.erb
<%= render "shared/form", listing: @listing %>

app/views/listings/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1580894908361-967195033215?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80);">
  <div id ="index-banner" class="container">
    <h1><strong>Our Amazing Tutors</strong></h1>
    <p>Get in touch with our devs today!</p>
  </div>
</div>
<div class="main-container p-6 m-5">
  <% @listings.each do |listing| %>
      <div class="index-card">
      <%= link_to listing do %>
      <% if listing.photo.attached? %>
        <%= cl_image_tag listing.photo.key %>
      <% end %>
        <div class="index-card-content">
          <h2> <%= "#{listing.user.first_name} #{listing.user.last_name}" %></h2>
          <h5> <%= listing.title %></h5>
          <div class="index-card-flex">
            <h6> £<%= listing.price %>/ph </h6>
            <%= link_to "Book Now", new_listing_booking_path(listing), class: "btn btn-gradient"  %>
          </div>
        </div>
      <% end %>
      </div>
  <% end %>
</div>

  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Rent-a-Dev <i class="fas fa-terminal"></i>
    </div>
</div>

app/views/listings/new.html.erb
<%= render "shared/form", listing: @listing %>

app/views/listings/show.html.erb
<h1 id="header-name-show"><%= "#{@listing.user.first_name} #{@listing.user.last_name}" %></h1>


<div class="show-container">
  <div class="index-card">
    <img src="https://images.unsplash.com/flagged/photo-1570612861542-284f4c12e75f?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80" alt="listing-tutor">
    <div class="index-card-content">
      <h2> <%= "#{@listing.user.first_name} #{@listing.user.last_name}" %></h2>
      <%# <h5> <%= @listing.title %></h5>
      <div class="index-card-flex">
        <h6> £<%= @listing.price %>/ph </h6>
        <%= link_to "Book Now", new_listing_booking_path(@listing), class: "btn btn-gradient"  %>
      </div>
    </div>
  </div>
  <div class="show-info-right-box">
    <div class="show-details-box">
    <h2> <%= "Hello, I'm #{@listing.user.first_name}!"%></h2>
    <h3> <%= @listing.title %> </h3>
    <h5> <%= "#{@listing.description}" %> </h5>
    </div>
    <div class="show-buttons-box">
      <div id="showbtn" class="show-buttons-space"><%= link_to "Delete", listing_path(@listing), class: "btn btn-gradient", method: :delete, data: {confirm: "Are you sure?"} %></div>
      <div id="showbtn" class="show-buttons-space"><%= link_to "Edit", edit_listing_path , class: "btn btn-gradient" %></div>
      <div id="showbtn" class="show-buttons-space"><%= link_to "Back", listings_path, class: "btn btn-back btn-gradient" %></div>
    </div>
  </div>
</div>


<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Rent-a-Dev <i class="fas fa-terminal"></i>
  </div>
</div>

<%# <%= link_to "Delete", listing_path(@listing), class: "btn btn-gradient", method: :delete, data: {confirm: "Are you sure?"}  %>
<%# <span><%= link_to "Edit", edit_listing_path , class: "btn btn-gradient"</span> %>
<%# <span><%= link_to "Back", listings_path, class: "btn btn-back btn-gradient"</span> %>

app/views/pages/home.html.erb
<%# <h1>RENT-A-DEV</h1> %>
<head>
</head>
<body>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1534665482403-a909d0d97c67?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80);">
    <div class="container">
      <h1><strong>Rent-a-Dev</strong></h1>
      <p>Find your coding tutor today</p>
    <%#---------- Code for serach bar--------- %>
      <div class="search-bar">
        <%= render "shared/searchbar" %>
      </div>
    <%#---------- Code for serach bar--------- %>
      <%# <%= link_to "Browse tutors", listings_path, class: "btn btn-gradient" %>
    </div>
  </div>

  <h1 id="our-tutors-header" style="text-indent: 0.5em";> Our Best Rated Tutors</h1>

  <div class="home-card-container">
    <div class="home-cards">
        <div class="home-card">
          <%# <%= link_to listings_path do Can't add link to booking until seed is done  %>
            <img src="https://constructionmaguk.co.uk/wp-content/uploads/2018/06/do-developer-profile.png" alt="listing-tutor">
            <div class="home-card-content">
              <h2>Dan Sterling</h2>
              <h5>Ruby/Python</h5>
              <div class="home-card-flex">
                <h6>£20/ph</h6>
                <a class="card-book-button">Book Now</a>
              </div>
            </div>
        <%# <% end - See comment above %>
      </div>

      <div class="home-card">
        <img src="https://miro.medium.com/max/1400/1*M7nNCFBIGyf13xQ7gY0swA.jpeg" alt="listing-tutor">
         <div class="home-card-content">
          <h2>Hannah Tow</h2>
          <h5>CSS/Html</h5>
          <div class="home-card-flex">
            <h6>£60/ph</h6>
            <a class="card-book-button">Book Now</a>
          </div>
        </div>
      </div>

      <div class="home-card">
        <img src="https://pixomatic.us/blog/wp-content/uploads/2019/11/pixomatic_1572877263963.png" alt="listing-tutor">
        <div class="home-card-content">
          <h2>Jane Morris</h2>
          <h5>Ruby/JavaScript</h5>
          <div class="home-card-flex">
            <h6>£35/ph</h6>
            <a class="card-book-button">Book Now</a>
          </div>
        </div>
      </div>
    </div>

    <div class="how-it-cards-container">
      <h2 id="how-header">How It Works</h2>
      <div class="how-it-cards">
        <div class="how-it-card">
          <img class ="circle-img" src="https://images.unsplash.com/photo-1537884944318-390069bb8665?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80">
          <div class="how-it-card-info">
            <h4>Find a Subject</h4>
            <p>Search for what subject you want to learn</p>
          </div>
        </div>
        <div class="how-it-card">
          <img class ="circle-img" src="https://images.unsplash.com/photo-1521931961826-fe48677230a5?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80">
          <div class="how-it-card-info">
            <h4>Reach Out</h4>
            <p>Get in touch with one of our tutors </p>
          </div>
        </div>
        <div class="how-it-card">
          <img class ="circle-img" src="https://images.unsplash.com/photo-1514996937319-344454492b37?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80">
          <div class="how-it-card-info">
            <h4>Learn To Code</h4>
            <p>Collaborate and learn with your tutor</p>
          </div>
        </div>
      </div>
    </div>
  </div>


  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      Rent-a-Dev <i class="fas fa-terminal"></i>
    </div>
  </div>
</body>

app/views/shared/_footer.html.erb
  <div class="footer">
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-instagram"></i></a>
      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
    <div class="footer-copyright">
      This footer is made with <i class="fas fa-heart"></i>
    </div>
  </div>

app/views/shared/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">
    <h1>Register as a Tutor</h1>
<%= simple_form_for(listing) do |f| %>
  <%= f.input :title, label: 'What coding languages can you teach?'%>
  <%= f.input :description, label: 'Tell us about your qualifications' %>
  <%= f.input :price,  label: 'How much do you charge per hour? (£)' %>
  <%= f.submit 'Create Tutor Profile', class: 'btn-gradient' %>
<% end %>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to request.base_url, class: "navbar-brand" do %>
  <%# ^need to insert link to homepage^ %>
  <i class="fas fa-terminal"></i>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>



  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", request.base_url , class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Become a tutor", new_listing_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">

        <% if current_user.avatar.attached? %>

          <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= cl_image_tag "j2iqdvjpx4gayzgvswa4rymp0xd7", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My bookings", my_bookings_path, class: "nav-link" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>

  </div>
</div>

app/views/shared/_searchbar.html.erb
<div class="container">
  <div class="form-row">
    <div>
      <%= form_tag listings_path, method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: "Search for anything"
        %>
        <%= submit_tag "Search", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>